// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmozotvmwlgmyxsrasxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtb3pvdHZtd2xnbXl4c3Jhc3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNzc1MTEsImV4cCI6MjA2Mjc1MzUxMX0.YqeKvHCItpqXg8tPVtduD3M4MdAPMAoHYwRzQVU2m8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);